[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
BlochSimulators = "2c9a3a5d-4a8d-4ca7-a6c9-04a38836deab"
ComputationalResources = "ed09eef8-17a6-5b46-8889-db040fac31e3"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
ImagePhantoms = "71a99df6-f52c-4da1-bd2a-69d6f37f3252"
ImageView = "86fae568-95e7-573e-a6b2-d8a6b900c9ef"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
PythonPlot = "274fc56d-3b97-40fa-a1cd-1b4a50311bf9"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"

[compat]
BlochSimulators = "0.2.5"
Documenter = "0.27"
